name: Publish Beta Package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    uses: ./.github/actions/publish.yml
    secrets: inherit
