name: Publish Beta Package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-package-npm:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
